name: Publish plugin

on:
  release:
    types: [published, created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        key: ${{ secrets.GRADLE_PUBLISH_KEY }}
        secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    - name: Build with Gradle
      run: ./gradlew publishPlugins -Pgradle.publish.key=${{ key }} -Pgradle.publish.secret=${{ secret }}
